import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card/Card';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';

import { getWeatherForecastData } from '../lib/weather';
import SearchBox from '../components/SearchBox/SearchBox';

export default function Home({ weatherData }) {
  const [location, setLocation] = useState('');
  const [weatherForecastData, setWeatherForecastData] = useState(weatherData);
  console.log('weatherData', weatherData);

  return (
    <div className={styles.container}>
      <Head>
        <title>WeatherIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen justify-center">
        <div className="w-4/5">
          <div className="grid grid-rows-3 grid-cols-3 h-screen">
            <div className="col-start-2 col-end-2 col-span-3 place-self-stretch self-center">
              <SearchBox
                location={location}
                setLocation={setLocation}
                setWeatherForecastData={setWeatherForecastData}
              />
            </div>

            <div className="row-start-2 col-start-2 col-end-2 col-span-3 place-self-center">
              <Card weatherData={weatherForecastData} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const weatherData = await getWeatherForecastData('Dublin');
  return {
    props: {
      weatherData,
    },
  };
}
