import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';
import styles from '../styles/Home.module.css';

import { getExampleWeatherData } from '../lib/weather';

export default function Home({ exampleWeatherData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>WeatherIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card weatherData={exampleWeatherData}></Card>
    </div>
  );
}

export async function getServerSideProps() {
  const exampleWeatherData = getExampleWeatherData();
  return {
    props: {
      exampleWeatherData,
    },
  };
}
